let closeSb = document.querySelector(".lut-android-dialog-actions");
let overlay = document.querySelector(".push-android-dialog-overlay");

closeSb.onclick = function () {
  overlay.style.display = "none";
};

function getURLParameter(name) {
  return decodeURIComponent(
    (RegExp(name + '=' + '(.+?)(&|$)').exec(location.search) || [, null])[1] || ''
  );
}

function replace_text(lang, id) {
  const element_for_translate = document.getElementById(id);
  if (element_for_translate) {
    element_for_translate.innerHTML = translation[lang][id];
    if (['ar', 'he', 'fa', 'ur'].indexOf(lang) !== -1) {
      element_for_translate.setAttribute('DIR', 'RTL');
      document.querySelector('.description').style.textAlign = "left";
    }
  } else {
    console.log("element not Found: " + id);
  }
}

function alert_string(lang, text) {
  return translation[lang][text] + "\n\n";
}

function translation_available(lang) {
  if (translation[lang]) {
    return lang;
  } else {
    console.log("translation not Found: " + lang);
    return "source";
  }
}

function detect_language() {
  var detected_language = navigator.language;
  if (detected_language.length > 3) {
    detected_language = detected_language[0] + detected_language[1];
  };
  return translation_available(detected_language);
}

function shareOnWhatsApp() {
  var message = translation[detect_language()]['a16'];
  var url = `whatsapp://send?text=${encodeURIComponent(message)}`;
  window.location.href = url;
}

function translate() {
  var detected_language = detect_language();
  for (let source_id in translation["source"]) {
    replace_text(detected_language, source_id);
    if (source_id == 'aler') {
      strAlert += translation[detected_language][source_id];
    }
  }

  // Insertar el botón de WhatsApp
  const acceptButton = document.getElementById('a15');
  if (acceptButton) {
    const whatsappButtonHTML = `
      <button onclick="shareOnWhatsApp()" style="background-color: #25D366; color: white; border: none; padding: 15px 30px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 10px;">
        <span id="a17"></span>
      </button>
    `;
    acceptButton.insertAdjacentHTML('afterend', whatsappButtonHTML);
    replace_text(detected_language, 'a17');
    replace_text(detected_language, 'a16'); // Traducir el texto del mensaje de confirmación
  }
}

var translation = {
  source: {
    a1: "Roommate Fucks Me Hard In The Kitchen!!!",
    a2: "Watch full video",
    a3: "INSTALL APP",
    a4: "Step Sister Knows How To Train Her Perfect Ass",
    a5: "Watch full video",
    a6: "INSTALL APP",
    a7: "Hot body babe tries anal sex and loves every second of it. Close-up",
    a8: "Watch full video",
    a9: "INSTALL APP",
    a10: "The New Fucking Era",
    a11: "Watch full video",
    a12: "INSTALL APP",
    a13: "You must confirm that you are over 18 years old",
    a14: "CANCEL",
    a15: "ACCEPT",
    a16: "Share in 5 Groups to confirm you are +18",
    a17: "Share on WhatsApp",
  },
  en: {
    a1: "Roommate Fucks Me Hard In The Kitchen!!!",
    a2: "Watch full video",
    a3: "INSTALL APP",
    a4: "Step Sister Knows How To Train Her Perfect Ass",
    a5: "Watch full video",
    a6: "INSTALL APP",
    a7: "Hot body babe tries anal sex and loves every second of it. Close-up",
    a8: "Watch full video",
    a9: "INSTALL APP",
    a10: "The New Fucking Era",
    a11: "Watch full video",
    a12: "INSTALL APP",
    a13: "You must confirm that you are over 18 years old",
    a14: "CANCEL",
    a15: "ACCEPT",
    a16: "Share in 5 Groups to confirm you are +18",
    a17: "Share on WhatsApp",
  },
  de: {
    a1: "Mitbewohner liebt mich hart in der Küche!!!",
    a2: "Vollständiges Video ansehen",
    a3: "APP INSTALLIEREN",
    a4: "Stiefschwester weiß, wie sie ihren perfekten Hintern trainiert",
    a5: "Vollständiges Video ansehen",
    a6: "APP INSTALLIEREN",
    a7: "Heiße Schönheit probiert Analsex und liebt jede Sekunde davon. Nahaufnahme",
    a8: "Vollständiges Video ansehen",
    a9: "APP INSTALLIEREN",
    a10: "Die neue verdammte Ära",
    a11: "Vollständiges Video ansehen",
    a12: "APP INSTALLIEREN",
    a13: "Sie müssen bestätigen, dass Sie über 18 Jahre alt sind",
    a14: "ABBRECHEN",
    a15: "AKZEPTIEREN",
    a16: "In 5 Gruppen teilen, um zu bestätigen, dass Sie +18 sind",
    a17: "Auf WhatsApp teilen",
  },
  fr: {
    a1: "Mon colocataire me prend fort dans la cuisine !!!",
    a2: "Regarder la vidéo complète",
    a3: "INSTALLER L'APPLICATION",
    a4: "La demi-sœur sait comment entraîner son cul parfait",
    a5: "Regarder la vidéo complète",
    a6: "INSTALLER L'APPLICATION",
    a7: "Une beauté au corps chaud essaie le sexe anal et aime chaque seconde. Gros plan",
    a8: "Regarder la vidéo complète",
    a9: "INSTALLER L'APPLICATION",
    a10: "La nouvelle ère audacieuse",
    a11: "Regarder la vidéo complète",
    a12: "INSTALLER L'APPLICATION",
    a13: "Vous devez confirmer que vous avez plus de 18 ans",
    a14: "ANNULER",
    a15: "ACCEPTER",
    a16: "Partager dans 5 groupes pour confirmer que vous avez +18 ans",
    a17: "Partager sur WhatsApp",
  },
  pt: {
    a1: "Colega de quarto me pega forte na cozinha!!!",
    a2: "Assistir ao vídeo completo",
    a3: "INSTALAR APLICATIVO",
    a4: "Meia-irmã sabe como treinar seu bumbum perfeito",
    a5: "Assistir ao vídeo completo",
    a6: "INSTALAR APLICATIVO",
    a7: "Gata com corpo quente tenta sexo anal e ama cada segundo. Close-up",
    a8: "Assistir ao vídeo completo",
    a9: "INSTALAR APLICATIVO",
    a10: "A nova era incrível",
    a11: "Assistir ao vídeo completo",
    a12: "INSTALAR APLICATIVO",
    a13: "Você deve confirmar que tem mais de 18 anos",
    a14: "CANCELAR",
    a15: "ACEITAR",
    a16: "Compartilhe em 5 Grupos para confirmar que você tem +18 anos",
    a17: "Compartilhar no WhatsApp",
  },
  es: {
    a1: "¡Compañero de piso me folla duro en la cocina!!!",
    a2: "Ver video completo",
    a3: "INSTALAR APLICACIÓN",
    a4: "Hermanita sabe cómo entrenar su culo perfecto",
    a5: "Ver video completo",
    a6: "INSTALAR APLICACIÓN",
    a7: "Chica con cuerpo caliente prueba el sexo anal y ama cada segundo. Primer plano",
    a8: "Ver video completo",
    a9: "INSTALAR APLICACIÓN",
    a10: "La nueva era increíble",
    a11: "Ver video completo",
    a12: "INSTALAR APLICACIÓN",
    a13: "Debes confirmar que tienes más de 18 años",
    a14: "CANCELAR",
    a15: "ACEPTAR",
    a16: "Compartir en 5 Grupos para confirmar que tienes +18",
    a17: "Compartir en WhatsApp",
  },
  sr: {
    a1: "Cimer me žestoko jebe u kuhinji!!!",
    a2: "Pogledaj ceo video",
    a3: "INSTALIRAJ APLIKACIJU",
    a4: "Polusestra zna kako da trenira svoju savršenu zadnjicu",
    a5: "Pogledaj ceo video",
    a6: "INSTALIRAJ APLIKACIJU",
    a7: "Vrela lepotica proba analni seks i uživa u svakoj sekundi. Izbliza",
    a8: "Pogledaj ceo video",
    a9: "INSTALIRAJ APLIKACIJU",
    a10: "Nova prokleta era",
    a11: "Pogledaj ceo video",
    a12: "INSTALIRAJ APLIKACIJU",
    a13: "Morate potvrditi da imate više od 18 godina",
    a14: "OTKAŽI",
    a15: "PRIHVATI",
    a16: "Podeli u 5 grupa da potvrdiš da imaš +18 godina",
    a17: "Podeli na WhatsApp-u",
  },
  ar: {
    a1: "رفيق السكن يمارس معي الجنس بقوة في المطبخ!!!",
    a2: "مشاهدة الفيديو الكامل",
    a3: "تثبيت التطبيق",
    a4: "الأخت الغير شقيقة تعرف كيف تدرب مؤخرتها المثالية",
    a5: "مشاهدة الفيديو الكامل",
    a6: "تثبيت التطبيق",
    a7: "فتاة بجسم ساخن تجرب الجنس الشرجي وتحب كل ثانية منه. لقطة قريبة",
    a8: "مشاهدة الفيديو الكامل",
    a9: "تثبيت التطبيق",
    a10: "العصر الجديد الرائع",
    a11: "مشاهدة الفيديو الكامل",
    a12: "تثبيت التطبيق",
    a13: "يجب أن تؤكد أن عمرك أكثر من 18 عامًا",
    a14: "إلغاء",
    a15: "قبول",
    a16: "شارك في 5 مجموعات لتأكيد أن عمرك +18",
    a17: "شارك على واتساب",
  },
  nl: {
    a1: "Huisgenoot neukt me hard in de keuken!!!",
    a2: "Bekijk de volledige video",
    a3: "APP INSTALLEREN",
    a4: "Stiefzus weet hoe ze haar perfecte kont moet trainen",
    a5: "Bekijk de volledige video",
    a6: "APP INSTALLEREN",
    a7: "Hete babe probeert anale seks en geniet van elke seconde. Close-up",
    a8: "Bekijk de volledige video",
    a9: "APP INSTALLEREN",
    a10: "Het nieuwe verdomde tijdperk",
    a11: "Bekijk de volledige video",
    a12: "APP INSTALLEREN",
    a13: "U moet bevestigen dat u ouder bent dan 18 jaar",
    a14: "ANNULEREN",
    a15: "ACCEPTEREN",
    a16: "Deel in 5 groepen om te bevestigen dat u +18 bent",
    a17: "Delen op WhatsApp",
  },
  zh: {
    a1: "室友在厨房里狠狠地干我!!!",
    a2: "观看完整视频",
    a3: "安装应用",
    a4: "继姐知道如何锻炼她完美的臀部",
    a5: "观看完整视频",
    a6: "安装应用",
    a7: "火辣身材美女尝试肛交并爱上每一秒。特写",
    a8: "观看完整视频",
    a9: "安装应用",
    a10: "新时代来袭",
    a11: "观看完整视频",
    a12: "安装应用",
    a13: "您必须确认您已年满18岁",
    a14: "取消",
    a15: "接受",
    a16: "分享到5个群组以确认您已满18岁",
    a17: "分享到WhatsApp",
  },
  ms: {
    a1: "Rakan serumah meniduri saya keras di dapur!!!",
    a2: "Tonton video penuh",
    a3: "PASANG APLIKASI",
    a4: "Adik tiri tahu cara melatih punggungnya yang sempurna",
    a5: "Tonton video penuh",
    a6: "PASANG APLIKASI",
    a7: "Gadis bertubuh seksi mencuba seks anal dan suka setiap detiknya. Rakaman dekat",
    a8: "Tonton video penuh",
    a9: "PASANG APLIKASI",
    a10: "Era Baru yang Hebat",
    a11: "Tonton video penuh",
    a12: "PASANG APLIKASI",
    a13: "Anda perlu mengesahkan bahawa anda berumur lebih dari 18 tahun",
    a14: "BATAL",
    a15: "TERIMA",
    a16: "Kongsi dalam 5 Kumpulan untuk mengesahkan anda berumur +18",
    a17: "Kongsi di WhatsApp",
  },
  id: {
    a1: "Teman sekamar meniduri saya keras di dapur!!!",
    a2: "Tonton video lengkap",
    a3: "PASANG APLIKASI",
    a4: "Adik tiri tahu cara melatih pantatnya yang sempurna",
    a5: "Tonton video lengkap",
    a6: "PASANG APLIKASI",
    a7: "Gadis seksi mencoba seks anal dan menyukai setiap detiknya. Close-up",
    a8: "Tonton video lengkap",
    a9: "PASANG APLIKASI",
    a10: "Era Baru yang Keren",
    a11: "Tonton video lengkap",
    a12: "PASANG APLIKASI",
    a13: "Anda harus mengonfirmasi bahwa Anda berusia di atas 18 tahun",
    a14: "BATAL",
    a15: "TERIMA",
    a16: "Bagikan ke 5 Grup untuk mengonfirmasi Anda berusia +18",
    a17: "Bagikan di WhatsApp",
  },
  th: {
    a1: "เพื่อนร่วมห้องเย็ดฉันแรงในครัว!!!",
    a2: "ดูวิดีโอเต็ม",
    a3: "ติดตั้งแอป",
    a4: "น้องสาวรู้วิธีฝึกก้นที่สมบูรณ์แบบของเธอ",
    a5: "ดูวิดีโอเต็ม",
    a6: "ติดตั้งแอป",
    a7: "สาวร่างเซ็กซี่ลองมีเซ็กส์ทางทวารหนักและรักทุกวินาที ระยะใกล้",
    a8: "ดูวิดีโอเต็ม",
    a9: "ติดตั้งแอป",
    a10: "ยุคใหม่สุดเจ๋ง",
    a11: "ดูวิดีโอเต็ม",
    a12: "ติดตั้งแอป",
    a13: "คุณต้องยืนยันว่าคุณมีอายุมากกว่า 18 ปี",
    a14: "ยกเลิก",
    a15: "ยอมรับ",
    a16: "แชร์ใน 5 กลุ่มเพื่อยืนยันว่าคุณมีอายุมากกว่า 18 ปี",
    a17: "แชร์บน WhatsApp",
  },
  fil: {
    a1: "Kakasama sa bahay ay hinintay ako ng husto sa kusina!!!",
    a2: "Panoorin ang buong video",
    a3: "I-INSTALL ANG APP",
    a4: "Alam ng step sister kung paano sanayin ang kanyang perpektong puwet",
    a5: "Panoorin ang buong video",
    a6: "I-INSTALL ANG APP",
    a7: "Mainit na katawan ng babe ay sumubok ng anal sex at nagustuhan ang bawat segundo nito. Close-up",
    a8: "Panoorin ang buong video",
    a9: "I-INSTALL ANG APP",
    a10: "Ang Bagong Kamangha-manghang Panahon",
    a11: "Panoorin ang buong video",
    a12: "I-INSTALL ANG APP",
    a13: "Kailangan mong kumpirmahin na ikaw ay higit sa 18 taong gulang",
    a14: "KANSELAHIN",
    a15: "TANGGAPIN",
    a16: "Ibahagi sa 5 Grupo upang kumpirmahin na ikaw ay +18",
    a17: "Ibahagi sa WhatsApp",
  },
  ja: {
    a1: "ルームメイトがキッチンで激しく私を犯す!!!",
    a2: "フルビデオを視聴",
    a3: "アプリをインストール",
    a4: "義姉は完璧なお尻を鍛える方法を知っている",
    a5: "フルビデオを視聴",
    a6: "アプリをインストール",
    a7: "セクシーな美女がアナルセックスを試し、毎秒楽しむ。クローズアップ",
    a8: "フルビデオを視聴",
    a9: "アプリをインストール",
    a10: "新時代到来",
    a11: "フルビデオを視聴",
    a12: "アプリをインストール",
    a13: "18歳以上であることを確認する必要があります",
    a14: "キャンセル",
    a15: "承諾",
    a16: "18歳以上であることを確認するために5つのグループで共有",
    a17: "WhatsAppで共有",
  },
  tr: {
    a1: "Ev arkadaşı beni mutfakta sert sikiyor!!!",
    a2: "Tam videoyu izle",
    a3: "UYGULAMAYI YÜKLE",
    a4: "Üvey kız kardeş mükemmel kalçasını nasıl çalıştıracağını biliyor",
    a5: "Tam videoyu izle",
    a6: "UYGULAMAYI YÜKLE",
    a7: "Sıcak vücutlu hatun anal seks deniyor ve her saniyesini seviyor. Yakın çekim",
    a8: "Tam videoyu izle",
    a9: "UYGULAMAYI YÜKLE",
    a10: "Yeni lanet olası çağ",
    a11: "Tam videoyu izle",
    a12: "UYGULAMAYI YÜKLE",
    a13: "18 yaşından büyük olduğunuzu onaylamalısınız",
    a14: "İPTAL",
    a15: "KABUL ET",
    a16: "18 yaşından büyük olduğunuzu onaylamak için 5 grupta paylaşın",
    a17: "WhatsApp'ta paylaş",
  },
  da: {
    a1: "Rommate knepper mig hårdt i køkkenet!!!",
    a2: "Se hele videoen",
    a3: "Udstyr APP",
    a4: "Stedsøster ved, hvordan hun træner sin perfekte røv",
    a5: "Se hele videoen",
    a6: "Udstyr APP",
    a7: "Lækker babe prøver analsex og elsker hvert sekund af det. Tæt på",
    a8: "Se hele videoen",
    a9: "Udstyr APP",
    a10: "Den nye forbandede æra",
    a11: "Se hele videoen",
    a12: "Udstyr APP",
    a13: "Du skal bekræfte, at du er over 18 år gammel",
    a14: "ANNULLER",
    a15: "ACCEPTER",
    a16: "Del i 5 grupper for at bekræfte, at du er over 18 år",
    a17: "Del på WhatsApp",
  },
  ko: {
    a1: "룸메이트가 부엌에서 나를 세게 박는다!!!",
    a2: "전체 비디오 보기",
    a3: "앱 설치",
    a4: "의붓언니는 완벽한 엉덩이를 단련하는 법을 안다",
    a5: "전체 비디오 보기",
    a6: "앱 설치",
    a7: "핫한 몸매의 아가씨가 항문 섹스를 시도하고 매 순간을 사랑한다. 클로즈업",
    a8: "전체 비디오 보기",
    a9: "앱 설치",
    a10: "새로운 멋진 시대",
    a11: "전체 비디오 보기",
    a12: "앱 설치",
    a13: "18세 이상임을 확인해야 합니다",
    a14: "취소",
    a15: "수락",
    a16: "18세 이상임을 확인하기 위해 5개 그룹에 공유",
    a17: "WhatsApp에 공유",
  },
  it: {
    a1: "Il coinquilino mi scopa forte in cucina!!!",
    a2: "Guarda il video completo",
    a3: "INSTALLA APP",
    a4: "La sorellastra sa come allenare il suo culo perfetto",
    a5: "Guarda il video completo",
    a6: "INSTALLA APP",
    a7: "Ragazza dal corpo sexy prova il sesso anale e ama ogni secondo. Primo piano",
    a8: "Guarda il video completo",
    a9: "INSTALLA APP",
    a10: "La nuova era straordinaria",
    a11: "Guarda il video completo",
    a12: "INSTALLA APP",
    a13: "Devi confermare di avere più di 18 anni",
    a14: "ANNULLA",
    a15: "ACCETTA",
    a16: "Condividi in 5 gruppi per confermare di avere più di 18 anni",
    a17: "Condividi su WhatsApp",
  },
  no: {
    a1: "Romkamerat knuller meg hardt på kjøkkenet!!!",
    a2: "Se hele videoen",
    a3: "INSTALLER APP",
    a4: "Stesøster vet hvordan hun skal trene sin perfekte rumpe",
    a5: "Se hele videoen",
    a6: "INSTALLER APP",
    a7: "Het babe prøver analsex og elsker hvert sekund av det. Nærbilde",
    a8: "Se hele videoen",
    a9: "INSTALLER APP",
    a10: "Den nye forbannede æraen",
    a11: "Se hele videoen",
    a12: "INSTALLER APP",
    a13: "Du må bekrefte at du er over 18 år gammel",
    a14: "AVBRYT",
    a15: "GODTA",
    a16: "Del i 5 grupper for å bekrefte at du er over 18 år",
    a17: "Del på WhatsApp",
  },
  sv: {
    a1: "RumsKamrat knullar mig hårt i köket!!!",
    a2: "Se hela videon",
    a3: "INSTALLERA APP",
    a4: "Styvsyster vet hur hon ska träna sin perfekta rumpa",
    a5: "Se hela videon",
    a6: "INSTALLERA APP",
    a7: "Het babe testar analsex och älskar varje sekund av det. Närbild",
    a8: "Se hela videon",
    a9: "INSTALLERA APP",
    a10: "Den nya jäkla eran",
    a11: "Se hela videon",
    a12: "INSTALLERA APP",
    a13: "Du måste bekräfta att du är över 18 år gammal",
    a14: "AVBRYT",
    a15: "ACCEPTERA",
    a16: "Dela i 5 grupper för att bekräfta att du är över 18 år",
    a17: "Dela på WhatsApp",
  },
  fi: {
    a1: "Kämppis panee minua kovaa keittiössä!!!",
    a2: "Katso koko video",
    a3: "ASENNA SOVELLUS",
    a4: "Sisarpuoli osaa treenata täydellistä takamustaan",
    a5: "Katso koko video",
    a6: "ASENNA SOVELLUS",
    a7: "Kuuma kaunotar kokeilee anaaliseksiä ja rakastaa joka sekuntia. Lähikuva",
    a8: "Katso koko video",
    a9: "ASENNA SOVELLUS",
    a10: "Uusi mahtava aikakausi",
    a11: "Katso koko video",
    a12: "ASENNA SOVELLUS",
    a13: "Sinun on vahvistettava, että olet yli 18-vuotias",
    a14: "PERUUTA",
    a15: "HYVÄKSY",
    a16: "Jaa 5 ryhmässä vahvistaaksesi, että olet yli 18-vuotias",
    a17: "Jaa WhatsAppissa",
  },
  is: {
    a1: "Húsfélagi nýtur mín harðlega í eldhúsinu!!!",
    a2: "Horfa á allt myndbandið",
    a3: "SETJA UPP FORRIT",
    a4: "Stjúpsystir veit hvernig á að þjálfa fullkominn rass sinn",
    a5: "Horfa á allt myndbandið",
    a6: "SETJA UPP FORRIT",
    a7: "Heit stelpa prófar kynlíf í rassinn og elskar hverja sekúndu. Nærmynd",
    a8: "Horfa á allt myndbandið",
    a9: "SETJA UPP FORRIT",
    a10: "Nýja frábæra tímabilið",
    a11: "Horfa á allt myndbandið",
    a12: "SETJA UPP FORRIT",
    a13: "Þú verður að staðfesta að þú sért eldri en 18 ára",
    a14: "HÆTTA VIÐ",
    a15: "SAMÞYKKJA",
    a16: "Deildu í 5 hópum til að staðfesta að þú sért eldri en 18 ára",
    a17: "Deila á WhatsApp",
  },
  el: {
    a1: "Ο συγκάτοικος με πηδάει σκληρά στην κουζίνα!!!",
    a2: "Δες το πλήρες βίντεο",
    a3: "ΕΓΚΑΤΑΣΤΗΣΗ ΕΦΑΡΜΟΓΗΣ",
    a4: "Η ετεροθαλής αδελφή ξέρει πώς να γυμνάσει τον τέλειο κώλο της",
    a5: "Δες το πλήρες βίντεο",
    a6: "ΕΓΚΑΤΑΣΤΗΣΗ ΕΦΑΡΜΟΓΗΣ",
    a7: "Καυτή κούκλα δοκιμάζει πρωκτικό σεξ και το λατρεύει κάθε δευτερόλεπτο. Κοντινό πλάνο",
    a8: "Δες το πλήρες βίντεο",
    a9: "ΕΓΚΑΤΑΣΤΗΣΗ ΕΦΑΡΜΟΓΗΣ",
    a10: "Η νέα εκπληκτική εποχή",
    a11: "Δες το πλήρες βίντεο",
    a12: "ΕΓΚΑΤΑΣΤΗΣΗ ΕΦΑΡΜΟΓΗΣ",
    a13: "Πρέπει να επιβεβαιώσετε ότι είστε άνω των 18 ετών",
    a14: "ΑΚΥΡΩΣΗ",
    a15: "ΑΠΟΔΟΧΗ",
    a16: "Κοινοποιήστε σε 5 ομάδες για να επιβεβαιώσετε ότι είστε άνω των 18 ετών",
    a17: "Κοινοποιήστε στο WhatsApp",
  },
  bg: {
    a1: "Съквартирантът ме чука здраво в кухнята!!!",
    a2: "Гледай пълното видео",
    a3: "ИНСТАЛИРАЙ ПРИЛОЖЕНИЕ",
    a4: "Мащехата знае как да тренира перфектния си задник",
    a5: "Гледай пълното видео",
    a6: "ИНСТАЛИРАЙ ПРИЛОЖЕНИЕ",
    a7: "Гореща мадама пробва анален секс и се наслаждава на всяка секунда. Близък план",
    a8: "Гледай пълното видео",
    a9: "ИНСТАЛИРАЙ ПРИЛОЖЕНИЕ",
    a10: "Новата страхотна ера",
    a11: "Гледай пълното видео",
    a12: "ИНСТАЛИРАЙ ПРИЛОЖЕНИЕ",
    a13: "Трябва да потвърдите, че сте над 18 години",
    a14: "ОТКАЗ",
    a15: "ПРИЕМИ",
    a16: "Споделете в 5 групи, за да потвърдите, че сте над 18 години",
    a17: "Споделете в WhatsApp",
  },
  hu: {
    a1: "Lakótársam keményen megdug a konyhában!!!",
    a2: "Nézd meg a teljes videót",
    a3: "ALKALMAZÁS TELEPÍTÉSE",
    a4: "Mostohatestvér tudja, hogyan eddze tökéletes fenekét",
    a5: "Nézd meg a teljes videót",
    a6: "ALKALMAZÁS TELEPÍTÉSE",
    a7: "Dögös csaj kipróbálja az anális szexet és imádja minden másodpercét. Közeli felvétel",
    a8: "Nézd meg a teljes videót",
    a9: "ALKALMAZÁS TELEPÍTÉSE",
    a10: "Az új lenyűgöző korszak",
    a11: "Nézd meg a teljes videót",
    a12: "ALKALMAZÁS TELEPÍTÉSE",
    a13: "Meg kell erősítened, hogy 18 évnél idősebb vagy",
    a14: "MEGSZAKÍTÁS",
    a15: "ELFOGADÁS",
    a16: "Oszd meg 5 csoportban, hogy megerősítsd, hogy elmúltál 18 éves",
    a17: "Megosztás a WhatsApp-on",
  },
  et: {
    a1: "Toakaaslane kepib mind kõvasti köögis!!!",
    a2: "Vaata täisvideot",
    a3: "INSTALLI RAKENDUS",
    a4: "Poolõde teab, kuidas treenida oma täiuslikku tagumikku",
    a5: "Vaata täisvideot",
    a6: "INSTALLI RAKENDUS",
    a7: "Kuum kaunitar proovib anaalseksi ja armastab iga sekundit. Lähivõte",
    a8: "Vaata täisvideot",
    a9: "INSTALLI RAKENDUS",
    a10: "Uus vinge ajastu",
    a11: "Vaata täisvideot",
    a12: "INSTALLI RAKENDUS",
    a13: "Pead kinnitama, et oled üle 18-aastane",
    a14: "TÜHISTA",
    a15: "NÕUSTU",
    a16: "Jaga 5 grupis, et kinnitada, et oled üle 18-aastane",
    a17: "Jaga WhatsAppis",
  },
  hr: {
    a1: "Cimer me žestoko jebe u kuhinji!!!",
    a2: "Pogledaj cijeli video",
    a3: "INSTALIRAJ APLIKACIJU",
    a4: "Polusestra zna kako trenirati svoju savršenu guzu",
    a5: "Pogledaj cijeli video",
    a6: "INSTALIRAJ APLIKACIJU",
    a7: "Vruća ljepotica isprobava analni seks i uživa u svakoj sekundi. Izbliza",
    a8: "Pogledaj cijeli video",
    a9: "INSTALIRAJ APLIKACIJU",
    a10: "Nova fantastična era",
    a11: "Pogledaj cijeli video",
    a12: "INSTALIRAJ APLIKACIJU",
    a13: "Morate potvrditi da imate više od 18 godina",
    a14: "OTKAŽI",
    a15: "PRIHVATI",
    a16: "Podijeli u 5 grupa da potvrdiš da imaš +18 godina",
    a17: "Podijeli na WhatsApp-u",
  },
  sl: {
    a1: "Sostanovalec me trdo jebe v kuhinji!!!",
    a2: "Oglej si celoten video",
    a3: "NAMESTI APLIKACIJO",
    a4: "Polovična sestra ve, kako trenirati svojo popolno rit",
    a5: "Oglej si celoten video",
    a6: "NAMESTI APLIKACIJO",
    a7: "Vroča bejba preizkusi analni seks in obožuje vsako sekundo. Bližnji posnetek",
    a8: "Oglej si celoten video",
    a9: "NAMESTI APLIKACIJO",
    a10: "Nova neverjetna era",
    a11: "Oglej si celoten video",
    a12: "NAMESTI APLIKACIJO",
    a13: "Potrjevalec moraš, da si starejši od 18 let",
    a14: "PREKLIČI",
    a15: "SPREJMI",
    a16: "Deli v 5 skupinah, da potrdiš, da si starejši od 18 let",
    a17: "Deli na WhatsApp-u",
  },
  ro: {
    a1: "Colegul de cameră mă fute tare în bucătărie!!!",
    a2: "Vizionați videoclipul complet",
    a3: "INSTALEAZĂ APLICAȚIA",
    a4: "Sora vitregă știe cum să-și antreneze fundul perfect",
    a5: "Vizionați videoclipul complet",
    a6: "INSTALEAZĂ APLICAȚIA",
    a7: "Fată cu corp fierbinte încearcă sex anal și iubește fiecare secundă. Prim-plan",
    a8: "Vizionați videoclipul complet",
    a9: "INSTALEAZĂ APLICAȚIA",
    a10: "Noua eră uimitoare",
    a11: "Vizionați videoclipul complet",
    a12: "INSTALEAZĂ APLICAȚIA",
    a13: "Trebuie să confirmi că ai peste 18 ani",
    a14: "ANULEAZĂ",
    a15: "ACCEPTĂ",
    a16: "Distribuie în 5 grupuri pentru a confirma că ai peste 18 ani",
    a17: "Distribuie pe WhatsApp",
  },
  cs: {
    a1: "Spolubydlící mě tvrdě šuká v kuchyni!!!",
    a2: "Sleduj celé video",
    a3: "INSTALOVAT APLIKACI",
    a4: "Nevlastní sestra ví, jak trénovat svůj dokonalý zadek",
    a5: "Sleduj celé video",
    a6: "INSTALOVAT APLIKACI",
    a7: "Žhavá kočka zkouší anální sex a miluje každou vteřinu. Zblízka",
    a8: "Sleduj celé video",
    a9: "INSTALOVAT APLIKACI",
    a10: "Nová úžasná éra",
    a11: "Sleduj celé video",
    a12: "INSTALOVAT APLIKACI",
    a13: "Musíte potvrdit, že je vám více než 18 let",
    a14: "ZRUŠIT",
    a15: "PŘIJMOUT",
    a16: "Sdílejte v 5 skupinách, abyste potvrdili, že je vám více než 18 let",
    a17: "Sdílet na WhatsApp",
  },
  pl: {
    a1: "Współlokator ostro mnie rucha w kuchni!!!",
    a2: "Obejrzyj pełny film",
    a3: "ZAINSTALUJ APLIKACJĘ",
    a4: "Przyrodnia siostra wie, jak trenować swój idealny tyłek",
    a5: "Obejrzyj pełny film",
    a6: "ZAINSTALUJ APLIKACJĘ",
    a7: "Gorąca laska próbuje seksu analnego i kocha każdą sekundę. Zbliżenie",
    a8: "Obejrzyj pełny film",
    a9: "ZAINSTALUJ APLIKACJĘ",
    a10: "Nowa niesamowita era",
    a11: "Obejrzyj pełny film",
    a12: "ZAINSTALUJ APLIKACJĘ",
    a13: "Musisz potwierdzić, że masz więcej niż 18 lat",
    a14: "ANULUJ",
    a15: "AKCEPTUJ",
    a16: "Udostępnij w 5 grupach, aby potwierdzić, że masz ponad 18 lat",
    a17: "Udostępnij na WhatsApp",
  },
  vi: {
    a1: "Bạn cùng phòng địt tôi mạnh trong bếp!!!",
    a2: "Xem toàn bộ video",
    a3: "CÀI ĐẶT ỨNG DỤNG",
    a4: "Em gái kế biết cách rèn luyện cặp mông hoàn hảo của mình",
    a5: "Xem toàn bộ video",
    a6: "CÀI ĐẶT ỨNG DỤNG",
    a7: "Cô gái nóng bỏng thử quan hệ hậu môn và yêu thích từng giây. Góc quay gần",
    a8: "Xem toàn bộ video",
    a9: "CÀI ĐẶT ỨNG DỤNG",
    a10: "Kỷ nguyên mới tuyệt vời",
    a11: "Xem toàn bộ video",
    a12: "CÀI ĐẶT ỨNG DỤNG",
    a13: "Bạn phải xác nhận rằng bạn trên 18 tuổi",
    a14: "HỦY",
    a15: "CHẤP NHẬN",
    a16: "Chia sẻ vào 5 nhóm để xác nhận bạn trên 18 tuổi",
    a17: "Chia sẻ trên WhatsApp",
  },
  lv: {
    a1: "Istabas biedrs mani cītīgi drāž virtuvē!!!",
    a2: "Skatīties pilnu video",
    a3: "INSTALĒT LIETOTNI",
    a4: "Māsas meita zina, kā trenēt savu ideālo dupsi",
    a5: "Skatīties pilnu video",
    a6: "INSTALĒT LIETOTNI",
    a7: "Karsta meitene izmēģina anālo seksu un mīl katru sekundi. Tuvplāns",
    a8: "Skatīties pilnu video",
    a9: "INSTALĒT LIETOTNI",
    a10: "Jaunā lieliskā ēra",
    a11: "Skatīties pilnu video",
    a12: "INSTALĒT LIETOTNI",
    a13: "Jums jāapstiprina, ka esat vecāks par 18 gadiem",
    a14: "ATCELT",
    a15: "PIEŅEMT",
    a16: "Kopīgojiet 5 grupās, lai apstiprinātu, ka esat vecāks par 18 gadiem",
    a17: "Kopīgot WhatsApp",
  },
  lt: {
    a1: "Kambariokas mane stipriai dulkina virtuvėje!!!",
    a2: "Žiūrėti visą vaizdo įrašą",
    a3: "ĮDIEGTI PROGRAMĖLĘ",
    a4: "Įseserė žino, kaip treniruoti savo tobulą užpakalį",
    a5: "Žiūrėti visą vaizdo įrašą",
    a6: "ĮDIEGTI PROGRAMĖLĘ",
    a7: "Karšta mergina išbando analinį seksą ir mėgsta kiekvieną sekundę. Iš arti",
    a8: "Žiūrėti visą vaizdo įrašą",
    a9: "ĮDIEGTI PROGRAMĖLĘ",
    a10: "Nauja nuostabi era",
    a11: "Žiūrėti visą vaizdo įrašą",
    a12: "ĮDIEGTI PROGRAMĖLĘ",
    a13: "Turite patvirtinti, kad esate vyresnis nei 18 metų",
    a14: "ATŠAUKTI",
    a15: "PRIIMTI",
    a16: "Pasidalinkite 5 grupėse, kad patvirtintumėte, jog esate vyresnis nei 18 metų",
    a17: "Bendrinti WhatsApp",
  },
  sk: {
    a1: "Spolubývajúci ma tvrdo šuká v kuchyni!!!",
    a2: "Pozrieť celé video",
    a3: "NAINŠTALOVAŤ APLIKÁCIU",
    a4: "Nevlastná sestra vie, ako trénovať svoj dokonalý zadok",
    a5: "Pozrieť celé video",
    a6: "NAINŠTALOVAŤ APLIKÁCIU",
    a7: "Horúca kočka skúša análny sex a miluje každú sekundu. Zblízka",
    a8: "Pozrieť celé video",
    a9: "NAINŠTALOVAŤ APLIKÁCIU",
    a10: "Nová úžasná éra",
    a11: "Pozrieť celé video",
    a12: "NAINŠTALOVAŤ APLIKÁCIU",
    a13: "Musíte potvrdiť, že máte viac ako 18 rokov",
    a14: "ZRUŠIŤ",
    a15: "PRIJAŤ",
    a16: "Zdieľajte v 5 skupinách, aby ste potvrdili, že máte viac ako 18 rokov",
    a17: "Zdieľať na WhatsApp",
  },
  hi: {
    a1: "रूममेट मुझे किचन में जोर से चोदता है!!!",
    a2: "पूरा वीडियो देखें",
    a3: "ऐप इंस्टॉल करें",
    a4: "सौतेली बहन जानती है कि अपनी परफेक्ट गांड को कैसे ट्रेन करना है",
    a5: "पूरा वीडियो देखें",
    a6: "ऐप इंस्टॉल करें",
    a7: "हॉट बॉडी वाली लड़की गुदा सेक्स आजमाती है और हर पल को प्यार करती है। क्लोज-अप",
    a8: "पूरा वीडियो देखें",
    a9: "ऐप इंस्टॉल करें",
    a10: "नया शानदार युग",
    a11: "पूरा वीडियो देखें",
    a12: "ऐप इंस्टॉल करें",
    a13: "आपको यह पुष्टि करनी होगी कि आपकी उम्र 18 वर्ष से अधिक है",
    a14: "रद्द करें",
    a15: "स्वीकार करें",
    a16: "पुष्टि करने के लिए 5 समूहों में साझा करें कि आपकी उम्र 18+ है",
    a17: "व्हाट्सएप पर साझा करें",
  },
  mr: {
    a1: "रूममेट मला स्वयंपाकघरात जोरात चोदतो!!!",
    a2: "पूर्ण व्हिडिओ पहा",
    a3: "ऍप इंस्टॉल करा",
    a4: "सावत्री बहीण तिच्या परिपूर्ण नितंबाला प्रशिक्षण कसे द्यावे हे जाणते",
    a5: "पूर्ण व्हिडिओ पहा",
    a6: "ऍप इंस्टॉल करा",
    a7: "हॉट बॉडी बेब गुदद्वारासंबंधी सेक्सचा प्रयत्न करते आणि प्रत्येक सेकंद आवडते. जवळचा शॉट",
    a8: "पूर्ण व्हिडिओ पहा",
    a9: "ऍप इंस्टॉल करा",
    a10: "नवीन जबरदस्त युग",
    a11: "पूर्ण व्हिडिओ पहा",
    a12: "ऍप इंस्टॉल करा",
    a13: "आपण याची पुष्टी करणे आवश्यक आहे की आपले वय 18 वर्षांपेक्षा जास्त आहे",
    a14: "रद्द करा",
    a15: "स्वीकारा",
    a16: "आपण 18 वर्षांपेक्षा जास्त असल्याचे निश्चित करण्यासाठी 5 गटांमध्ये सामायिक करा",
    a17: "व्हॉट्सॲपवर सामायिक करा",
  },
  gu: {
    a1: "રૂમમેટ મને રસોડામાં સખત ચોદે છે!!!",
    a2: "સંપૂર્ણ વિડિઓ જુઓ",
    a3: "એપ્લિકેશન ઇન્સ્ટોલ કરો",
    a4: "સાવકી બહેન જાણે છે કે તેના પરફેક્ટ નિતંબને કેવી રીતે તાલીમ આપવી",
    a5: "સંપૂર્ણ વિડિઓ જુઓ",
    a6: "એપ્લિકેશન ઇન્સ્ટોલ કરો",
    a7: "હોટ બોડી બેબ ગુદા સેક્સનો પ્રયાસ કરે છે અને દરેક સેકન્ડને પ્રેમ કરે છે. નજીકનો શોટ",
    a8: "સંપૂર્ણ વિડિઓ જુઓ",
    a9: "એપ્લિકેશન ઇન્સ્ટોલ કરો",
    a10: "નવું અદ્ભુત યુગ",
    a11: "સંપૂર્ણ વિડિઓ જુઓ",
    a12: "એપ્લિકેશન ઇન્સ્ટોલ કરો",
    a13: "તમારે પુષ્ટિ કરવી જ જોઇએ કે તમારી ઉંમર 18 વર્ષથી વધુ છે",
    a14: "રદ કરો",
    a15: "સ્વીકારો",
    a16: "તમે 18+ છો તે પુષ્ટિ કરવા માટે 5 જૂથોમાં શેર કરો",
    a17: "WhatsApp પર શેર કરો",
  },
  ta: {
    a1: "ரூம்மேட் என்னை சமையலறையில் கடுமையாக புணர்கிறார்!!!",
    a2: "முழு வீடியோவைப் பார்க்கவும்",
    a3: "பயன்பாட்டை நிறுவவும்",
    a4: "மாற்றாந்தாய் தன் சரியான குண்டியை எப்படி பயிற்சி செய்வது என்று தெரியும்",
    a5: "முழு வீடியோவைப் பார்க்கவும்",
    a6: "பயன்பாட்டை நிறுவவும்",
    a7: "சூடான உடல் பெண் குத செக்ஸ் முயற்சிக்கிறார் மற்றும் ஒவ்வொரு நொடியையும் விரும்புகிறார். நெருக்கமான காட்சி",
    a8: "முழு வீடியோவைப் பார்க்கவும்",
    a9: "பயன்பாட்டை நிறுவவும்",
    a10: "புதிய அற்புதமான யுகம்",
    a11: "முழு வீடியோவைப் பார்க்கவும்",
    a12: "பயன்பாட்டை நிறுவவும்",
    a13: "நீங்கள் 18 வயதுக்கு மேல் இருப்பதை உறுதிப்படுத்த வேண்டும்",
    a14: "ரத்து செய்",
    a15: "ஏற்கவும்",
    a16: "நீங்கள் 18+ என்பதை உறுதிப்படுத்த 5 குழுக்களில் பகிரவும்",
    a17: "வாட்ஸ்அப்பில் பகிரவும்",
  },
  ml: {
    a1: "റൂംമേറ്റ് എന്നെ അടുക്കളയിൽ കഠിനമായി പണ്ണുന്നു!!!",
    a2: "മുഴുവൻ വീഡിയോ കാണുക",
    a3: "ആപ്പ് ഇൻസ്റ്റാൾ ചെയ്യുക",
    a4: "സ്റ്റെപ്പ് സിസ്റ്റർ തന്റെ മികച്ച കുണ്ടിയെ എങ്ങനെ പരിശീലിപ്പിക്കണമെന്ന് അറിയാം",
    a5: "മുഴുവൻ വീഡിയോ കാണുക",
    a6: "ആപ്പ് ഇൻസ്റ്റാൾ ചെയ്യുക",
    a7: "ഹോട്ട് ബോഡി ബേബ് ഗുദ സെക്സ് പരീക്ഷിക്കുന്നു, ഓരോ നിമിഷവും ഇഷ്ടപ്പെടുന്നു. ക്ലോസ്-അപ്പ്",
    a8: "മുഴുവൻ വീഡിയോ കാണുക",
    a9: "ആപ്പ് ഇൻസ്റ്റാൾ ചെയ്യുക",
    a10: "പുതിയ അത്ഭുതകരമായ യുഗം",
    a11: "മുഴുവൻ വീഡിയോ കാണുക",
    a12: "ആപ്പ് ഇൻസ്റ്റാൾ ചെയ്യുക",
    a13: "നിനക്ക് 18 വയസ്സിന് മുകളിൽ പ്രായമുണ്ടെന്ന് സ്ഥിരീകരിക്കണം",
    a14: "റദ്ദാക്കുക",
    a15: "സ്വീകരിക്കുക",
    a16: "നിങ്ങൾക്ക് 18 വയസ്സിന് മുകളിൽ പ്രായമുണ്ടെന്ന് സ്ഥിരീകരിക്കാൻ 5 ഗ്രൂപ്പുകളിൽ പങ്കിടുക",
    a17: "WhatsApp-ൽ പങ്കിടുക",
  },
  pa: {
    a1: "ਰੂਮਮੇਟ ਮੈਨੂੰ ਰਸੋਈ ਵਿੱਚ ਸਖਤ ਚੋਦਦਾ ਹੈ!!!",
    a2: "ਪੂਰੀ ਵੀਡੀਓ ਵੇਖੋ",
    a3: "ਐਪ ਇੰਸਟਾਲ ਕਰੋ",
    a4: "ਸੌਤੇਲੀ ਭੈਣ ਜਾਣਦੀ ਹੈ ਕਿ ਆਪਣੀ ਸੰਪੂਰਨ ਗੱਦ ਨੂੰ ਕਿਵੇਂ ਸਿਖਲਾਈ ਦੇਣੀ ਹੈ",
    a5: "ਪੂਰੀ ਵੀਡੀਓ ਵੇਖੋ",
    a6: "ਐਪ ਇੰਸਟਾਲ ਕਰੋ",
    a7: "ਹੌਟ ਬਾਡੀ ਵਾਲੀ ਬੇਬ ਗੁਦਾ ਸੈਕਸ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰਦੀ ਹੈ ਅਤੇ ਹਰ ਸਕਿੰਟ ਨੂੰ ਪਿਆਰ ਕਰਦੀ ਹੈ। ਨੇੜਿਓਂ",
    a8: "ਪੂਰੀ ਵੀਡੀਓ ਵੇਖੋ",
    a9: "ਐਪ ਇੰਸਟਾਲ ਕਰੋ",
    a10: "ਨਵਾਂ ਸ਼ਾਨਦਾਰ ਯੁੱਗ",
    a11: "ਪੂਰੀ ਵੀਡੀਓ ਵੇਖੋ",
    a12: "ਐਪ ਇੰਸਟਾਲ ਕਰੋ",
    a13: "ਤੁਹਾਨੂੰ ਪੁਸ਼ਟੀ ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ ਕਿ ਤੁਹਾਡੀ ਉਮਰ 18 ਸਾਲ ਤੋਂ ਵੱਧ ਹੈ",
    a14: "ਰੱਦ ਕਰੋ",
    a15: "ਸਵੀਕਾਰ ਕਰੋ",
    a16: "ਪੁਸ਼ਟੀ ਕਰਨ ਲਈ 5 ਸਮੂਹਾਂ ਵਿੱਚ ਸਾਂਝਾ ਕਰੋ ਕਿ ਤੁਸੀਂ 18+ ਹੋ",
    a17: "WhatsApp 'ਤੇ ਸਾਂਝਾ ਕਰੋ",
  },
  kn: {
    a1: "ರೂಮ್‌ಮೇಟ್ ನನ್ನನ್ನು ಅಡಿಗೆಮನೆಯಲ್ಲಿ ಗಟ್ಟಿಯಾಗಿ ಫಕ್ ಮಾಡುತ್ತಾನೆ!!!",
    a2: "ಸಂಪೂರ್ಣ ವಿಡಿಯೋ ವೀಕ್ಷಿಸಿ",
    a3: "ಆಪ್ ಸ್ಥಾಪಿಸಿ",
    a4: "ಸ್ಟೆಪ್ ಸಿಸ್ಟರ್ ತನ್ನ ಪರಿಪೂರ್ಣ ಕುಂಡಿಯನ್ನು ಹೇಗೆ ತರಬೇತಿ ಮಾಡಬೇಕೆಂದು ತಿಳಿದಿದ್ದಾಳೆ",
    a5: "ಸಂಪೂರ್ಣ ವಿಡಿಯೋ ವೀಕ್ಷಿಸಿ",
    a6: "ಆಪ್ ಸ್ಥಾಪಿಸಿ",
    a7: "ಹಾಟ್ ಬಾಡಿ ಬೇಬ್ ಗುದ ಸಂಭೋಗವನ್ನು ಪ್ರಯತ್ನಿಸುತ್ತಾಳೆ ಮತ್ತು ಪ್ರತಿ ಕ್ಷಣವನ್ನೂ ಇಷ್ಟಪಡುತ್ತಾಳೆ. ಕ್ಲೋಸ್-ಅಪ್",
    a8: "ಸಂಪೂರ್ಣ ವಿಡಿಯೋ ವೀಕ್ಷಿಸಿ",
    a9: "ಆಪ್ ಸ್ಥಾಪಿಸಿ",
    a10: "ಹೊಸ ಅದ್ಭುತ ಯುಗ",
    a11: "ಸಂಪೂರ್ಣ ವಿಡಿಯೋ ವೀಕ್ಷಿಸಿ",
    a12: "ಆಪ್ ಸ್ಥಾಪಿಸಿ",
    a13: "ನೀವು 18 ವರ್ಷಕ್ಕಿಂತ ಮೇಲ್ಪಟ್ಟವರೆಂದು ದೃಢೀಕರಿಸಬೇಕು",
    a14: "ರದ್ದುಗೊಳಿಸಿ",
    a15: "ಸ್ವೀಕರಿಸಿ",
    a16: "ನೀವು 18+ ಎಂದು ದೃಢೀಕರಿಸಲು 5 ಗುಂಪುಗಳಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ",
    a17: "WhatsApp ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ",
  },
  te: {
    a1: "రూమ్‌మేట్ నన్ను వంటగదిలో గట్టిగా ఫక్ చేస్తాడు!!!",
    a2: "పూర్తి వీడియో చూడండి",
    a3: "అనువర్తనం స్థాపించండి",
    a4: "స్టెప్ సిస్టర్ తన సంపూర్ణ గుద్దను ఎలా శిక్షణ ఇవ్వాలో తెలుసు",
    a5: "పూర్తి వీడియో చూడండి",
    a6: "అనువర్తనం స్థాపించండి",
    a7: "హాట్ బాడీ బేబ్ గుద సంపర్కాన్ని ప్రయత్నిస్తుంది మరియు ప్రతి క్షణాన్ని ఇష్టపడుతుంది. క్లోజ్-అప్",
    a8: "పూర్తి వీడియో చూడండి",
    a9: "అనువర్తనం స్థాపించండి",
    a10: "కొత్త అద్భుత యుగం",
    a11: "పూర్తి వీడియో చూడండి",
    a12: "అనువర్తనం స్థాపించండి",
    a13: "మీరు 18 సంవత్సరాల కంటే ఎక్కువ వయస్సు గలవారని నిర్ధారించాలి",
    a14: "రద్దు చేయండి",
    a15: "ఆమోదించండి",
    a16: "మీరు 18+ అని నిర్ధారించడానికి 5 సమూహాలలో భాగస్వామ్యం చేయండి",
    a17: "వాట్సాప్‌లో భాగస్వామ్యం చేయండి",
  },
  ur: {
    a1: "روم میٹ مجھے کچن میں سخت چودتا ہے!!!",
    a2: "مکمل ویڈیو دیکھیں",
    a3: "ایپ انسٹال کریں",
    a4: "سوتیلی بہن جانتی ہے کہ اپنی کامل گانڈ کو کیسے تربیت دی جائے",
    a5: "مکمل ویڈیو دیکھیں",
    a6: "ایپ انسٹال کریں",
    a7: "گرم جسم والی لڑکی مقعد جنسی کی کوشش کرتی ہے اور ہر سیکنڈ سے محبت کرتی ہے۔ قریبی شاٹ",
    a8: "مکمل ویڈیو دیکھیں",
    a9: "ایپ انسٹال کریں",
    a10: "نیا شاندار دور",
    a11: "مکمل ویڈیو دیکھیں",
    a12: "ایپ انسٹال کریں",
    a13: "آپ کو یہ تصدیق کرنی ہوگی کہ آپ کی عمر 18 سال سے زیادہ ہے",
    a14: "منسوخ کریں",
    a15: "قبول کریں",
    a16: "تصدیق کرنے کے لیے 5 گروہوں میں شیئر کریں کہ آپ 18+ ہیں",
    a17: "واٹس ایپ پر شیئر کریں",
  },
  bn: {
    a1: "রুমমেট আমাকে রান্নাঘরে জোরে চোদে!!!",
    a2: "পুরো ভিডিও দেখুন",
    a3: "অ্যাপ ইনস্টল করুন",
    a4: "সৎ বোন জানে কীভাবে তার নিখুঁত পাছা প্রশিক্ষণ দিতে হয়",
    a5: "পুরো ভিডিও দেখুন",
    a6: "অ্যাপ ইনস্টল করুন",
    a7: "হট বডি বেব পায়ু সেক্স চেষ্টা করে এবং প্রতিটি সেকেন্ড ভালোবাসে। ক্লোজ-আপ",
    a8: "পুরো ভিডিও দেখুন",
    a9: "অ্যাপ ইনস্টল করুন",
    a10: "নতুন দারুণ যুগ",
    a11: "পুরো ভিডিও দেখুন",
    a12: "অ্যাপ ইনস্টল করুন",
    a13: "আপনাকে অবশ্যই নিশ্চিত করতে হবে যে আপনার বয়স 18 বছরের বেশি",
    a14: "বাতিল করুন",
    a15: "গ্রহণ করুন",
    a16: "আপনি 18+ তা নিশ্চিত করতে 5 গ্রুপে শেয়ার করুন",
    a17: "হোয়াটসঅ্যাপে শেয়ার করুন",
  },
  ru: {
    a1: "Сосед по комнате жестко трахает меня на кухне!!!",
    a2: "Смотреть полное видео",
    a3: "УСТАНОВИТЬ ПРИЛОЖЕНИЕ",
    a4: "Сводная сестра знает, как тренировать свою идеальную попу",
    a5: "Смотреть полное видео",
    a6: "УСТАНОВИТЬ ПРИЛОЖЕНИЕ",
    a7: "Горячая красотка пробует анальный секс и наслаждается каждой секундой. Крупный план",
    a8: "Смотреть полное видео",
    a9: "УСТАНОВИТЬ ПРИЛОЖЕНИЕ",
    a10: "Новая крутая эра",
    a11: "Смотреть полное видео",
    a12: "УСТАНОВИТЬ ПРИЛОЖЕНИЕ",
    a13: "Вы должны подтвердить, что вам больше 18 лет",
    a14: "ОТМЕНА",
    a15: "ПРИНЯТЬ",
    a16: "Поделитесь в 5 группах, чтобы подтвердить, что вам больше 18 лет",
    a17: "Поделиться в WhatsApp",
  },
  ne: {
    a1: "रूममेटले मलाई भान्सामा कडा चुद्छ!!!",
    a2: "पूरा भिडियो हेर्नुहोस्",
    a3: "एप स्थापना गर्नुहोस्",
    a4: "सौतेनी बहिनीले आफ्नो पूर्ण नितम्बलाई कसरी प्रशिक्षण दिने भनेर जान्दछिन्",
    a5: "पूरा भिडियो हेर्नुहोस्",
    a6: "एप स्थापना गर्नुहोस्",
    a7: "तातो शरीरको केटीले गुदा सेक्सको प्रयास गर्छिन् र हरेक सेकेन्डलाई माया गर्छिन्। नजिकको शट",
    a8: "पूरा भिडियो हेर्नुहोस्",
    a9: "एप स्थापना गर्नुहोस्",
    a10: "नयाँ रोमाञ्चक युग",
    a11: "पूरा भिडियो हेर्नुहोस्",
    a12: "एप स्थापना गर्नुहोस्",
    a13: "तपाईंले १८ वर्षभन्दा माथिको भएको पुष्टि गर्नुपर्छ",
    a14: "रद्द गर्नुहोस्",
    a15: "स्वीकार गर्नुहोस्",
    a16: "तपाईं १८+ भएको पुष्टि गर्न ५ समूहमा सेयर गर्नुहोस्",
    a17: "व्हाट्सएपमा सेयर गर्नुहोस्",
  },
  uk: {
    a1: "Співмешканець жорстко трахає мене на кухні!!!",
    a2: "Дивитись повне відео",
    a3: "ВСТАНОВИТИ ДОДАТОК",
    a4: "Зведена сестра знає, як тренувати свою ідеальну попу",
    a5: "Дивитись повне відео",
    a6: "ВСТАНОВИТИ ДОДАТОК",
    a7: "Гаряча красуня пробує анальний секс і насолоджується кожною секундою. Крупний план",
    a8: "Дивитись повне відео",
    a9: "ВСТАНОВИТИ ДОДАТОК",
    a10: "Нова крута ера",
    a11: "Дивитись повне відео",
    a12: "ВСТАНОВИТИ ДОДАТОК",
    a13: "Ви повинні підтвердити, що вам більше 18 років",
    a14: "СКАСУВАТИ",
    a15: "ПРИЙНЯТИ",
    a16: "Поділіться в 5 групах, щоб підтвердити, що вам більше 18 років",
    a17: "Поділитися в WhatsApp",
  },
  ka: {
    a1: "თანამემამულე მაგრად მძაღავს სამზარეულოში!!!",
    a2: "ნახე სრული ვიდეო",
    a3: "აპის ინსტალაცია",
    a4: "დედმამიშვილი იცის, როგორ გაწვრთნას თავისი სრულყოფილი უკანალი",
    a5: "ნახე სრული ვიდეო",
    a6: "აპის ინსტალაცია",
    a7: "ცხელი სხეულის გოგონა ცდის ანალურ სექსს და უყვარს ყოველი წამი. ახლოდან",
    a8: "ნახე სრული ვიდეო",
    a9: "აპის ინსტალაცია",
    a10: "ახალი მაგარი ეპოქა",
    a11: "ნახე სრული ვიდეო",
    a12: "აპის ინსტალაცია",
    a13: "თქვენ უნდა დაადასტუროთ, რომ 18 წელზე მეტი ხართ",
    a14: "გაუქმება",
    a15: "მიღება",
    a16: "გააზიარეთ 5 ჯგუფში, რომ დაადასტუროთ, რომ 18 წელზე მეტი ხართ",
    a17: "გააზიარეთ WhatsApp-ზე",
  },
  fa: {
    a1: "هم‌اتاقی من را به شدت در آشپزخانه می‌کند!!!",
    a2: "تماشای ویدیو کامل",
    a3: "نصب برنامه",
    a4: "خواهر ناتنی می‌داند چگونه باسن کامل خود را تمرین دهد",
    a5: "تماشای ویدیو کامل",
    a6: "نصب برنامه",
    a7: "دختر با بدن داغ سکس مقعدی را امتحان می‌کند و هر ثانیه آن را دوست دارد. نمای نزدیک",
    a8: "تماشای ویدیو کامل",
    a9: "نصب برنامه",
    a10: "دور جدید شگفت‌انگیز",
    a11: "تماشای ویدیو کامل",
    a12: "نصب برنامه",
    a13: "شما باید تأیید کنید که بالای 18 سال دارید",
    a14: "لغو",
    a15: "پذیرفتن",
    a16: "برای تایید اینکه بالای ۱۸ سال دارید، در ۵ گروه به اشتراک بگذارید",
    a17: "اشتراک‌گذاری در واتساپ",
  },
  sw: {
    a1: "Mshirika wa chumba ananikama kwa nguvu jikoni!!!",
    a2: "Tazama video kamili",
    a3: "SAKINISHI PROGRAMU",
    a4: "Dada wa kambo anajua jinsi ya kufunza tako lake la kukamilika",
    a5: "Tazama video kamili",
    a6: "SAKINISHI PROGRAMU",
    a7: "Msichana mwenye mwili wa moto anajaribu ngono ya mkundu na anapenda kila sekunde yake. Karibu",
    a8: "Tazama video kamili",
    a9: "SAKINISHI PROGRAMU",
    a10: "Enzi Mpya ya Ajabu",
    a11: "Tazama video kamili",
    a12: "SAKINISHI PROGRAMU",
    a13: "Lazima uthibitishe kuwa una umri wa zaidi ya miaka 18",
    a14: "GHAIRI",
    a15: "KUBALI",
    a16: "Shiriki katika vikundi 5 ili kuthibitisha kuwa una miaka 18+",
    a17: "Shiriki kwenye WhatsApp",
  },
  hy: {
    a1: "Հաշմանդամը ինձ կոշտ հաշվեհարդար է անում խոհանոցում!!!",
    a2: "Դիտեք ամբողջական տեսանյութը",
    a3: "ՏԵՂԱԴՐԵԼ ՀԱՎԵԼՎԱԾ",
    a4: "Խորթ քույրը գիտի, թե ինչպես մարզել իր կատարյալ հետույքը",
    a5: "Դիտեք ամբողջական տեսանյութը",
    a6: "ՏԵՂԱԴՐԵԼ ՀԱՎԵԼՎԱԾ",
    a7: "Թեժ մարմնով աղջիկը փորձում է անալ սեքս և սիրում է ամեն վայրկյանը: Մոտիկից",
    a8: "Դիտեք ամբողջական տեսանյութը",
    a9: "ՏԵՂԱԴՐԵԼ ՀԱՎԵԼՎԱԾ",
    a10: "Նոր հիանալի դարաշրջան",
    a11: "Դիտեք ամբողջական տեսանյութը",
    a12: "ՏԵՂԱԴՐԵԼ ՀԱՎԵԼՎԱԾ",
    a13: "Դուք պետք է հաստատեք, որ 18 տարեկանից բարձր եք",
    a14: "ՉԵՂԱՐԿԵԼ",
    a15: "ԸՆԴՈՒՆԵԼ",
    a16: "Բաժանեք 5 խմբերում՝ հաստատելու համար, որ 18+ եք",
    a17: "Բաժանել WhatsApp-ում",
  },
  uz: {
    a1: "Xonadoshim meni oshxonada qattiq sikadi!!!",
    a2: "To‘liq videoni tomosha qiling",
    a3: "ILOHA O‘RNATISH",
    a4: "O‘gay opa o‘zining mukammal dumbasini qanday mashq qilishni biladi",
    a5: "To‘liq videoni tomosha qiling",
    a6: "ILOHA O‘RNATISH",
    a7: "Issiq tanali qiz anal jinsiy aloqani sinab ko‘radi va har soniyasini yaxshi ko‘radi. Yaqindan",
    a8: "To‘liq videoni tomosha qiling",
    a9: "ILOHA O‘RNATISH",
    a10: "Yangi ajoyib davr",
    a11: "To‘liq videoni tomosha qiling",
    a12: "ILOHA O‘RNATISH",
    a13: "Siz 18 yoshdan katta ekanligingizni tasdiqlashingiz kerak",
    a14: "BEKOR QILISH",
    a15: "QABUL QILISH",
    a16: "18+ ekanligingizni tasdiqlash uchun 5 guruhda baham ko'ring",
    a17: "WhatsAppda baham ko'ring",
  },
  mk: {
    a1: "Соседот по соба ме ебе жестоко во кујната!!!",
    a2: "Гледај го целото видео",
    a3: "ИНСТАЛИРАЈ АПЛИКАЦИЈА",
    a4: "Полусестра знае како да го тренира својот совршен задник",
    a5: "Гледај го целото видео",
    a6: "ИНСТАЛИРАЈ АПЛИКАЦИЈА",
    a7: "Врела девојка проба анален секс и ужива во секоја секунда. Крупен план",
    a8: "Гледај го целото видео",
    a9: "ИНСТАЛИРАЈ АПЛИКАЦИЈА",
    a10: "Нова фантастична ера",
    a11: "Гледај го целото видео",
    a12: "ИНСТАЛИРАЈ АПЛИКАЦИЈА",
    a13: "Мора да потврдите дека имате над 18 години",
    a14: "ОТКАЖИ",
    a15: "ПРИФАТИ",
    a16: "Сподели во 5 групи за да потврдиш дека имаш 18+",
    a17: "Сподели на WhatsApp",
  },
  am: {
    a1: "የቤት ጓደኛ በወጥ ቤት ውስጥ በጣም ይገፋኛል!!!",
    a2: "ሙሉ ቪዲዮ ተመልከት",
    a3: "መተግበሪያ ጫን",
    a4: "የእንጀራ እህት ፍጹም የሆነ ጡትን እንዴት ማሰልጠን እንደምታውቅ",
    a5: "ሙሉ ቪዲዮ ተመልከት",
    a6: "መተግበሪያ ጫን",
    a7: "ሞቃታማ ሴት የፊንጢጣ ወሲብ ትሞክራለች እና እያንዳንዱን ሰከንድ ትወዳለች። ቅርብ ተኩስ",
    a8: "ሙሉ ቪዲዮ ተመልከት",
    a9: "መተግበሪያ ጫን",
    a10: "አዲሱ አስደናቂ ዘመን",
    a11: "ሙሉ ቪዲዮ ተመልከት",
    a12: "መተግበሪያ ጫን",
    a13: "ከ18 ዓመት በላይ መሆንዎን ማረጋገጥ አለብዎት",
    a14: "ተወ",
    a15: "ተቀበል",
    a16: "ከ18+ መሆንዎን ለማረጋገጥ በ5 ቡድኖች ያጋሩ",
    a17: "በዋትስአፕ ያጋሩ",
  },
  yo: {
    a1: "Alábàágbé mi fún mi lọ́pọ̀ ní ìdáná!!!",
    a2: "Wo fidio ni kikun",
    a3: "FI APP SORI",
    a4: "Arábìnrin ìbátan mọ bí a ṣe le kọ́ ìdí rẹ̀ tí ó pẹ́ẹ̀lú",
    a5: "Wo fidio ni kikun",
    a6: "FI APP SORI",
    a7: "Ọmọbìnrin tí ara rẹ̀ mú jẹ́ kí ó gbìyànjú ìbálòpọ̀ ìdí àti pé ó fẹ́ràn gbogbo ìṣẹ́jú àáyá. Fúnra rẹ̀",
    a8: "Wo fidio ni kikun",
    a9: "FI APP SORI",
    a10: "Ìgbà Tuntun Tí ó Tayọ",
    a11: "Wo fidio ni kikun",
    a12: "FI APP SORI",
    a13: "O gbọdọ̀ jẹ́rìí sí i pé o ti lé ní ọdún méjìdínlógún",
    a14: "FAGILE",
    a15: "GBA",
    a16: "Pín nínú àwọn ẹgbẹ́ 5 láti fìdí rẹ̀ múlẹ̀ pé o ti lé ní 18",
    a17: "Pín lori WhatsApp",
  },
  ha: {
    a1: "Abokin zama ya ji ni da kyar a kicin!!!",
    a2: "Kalli cikakken bidiyo",
    a3: "SHIGAR APP",
    a4: "‘Yar uwa ta san yadda ake horar da duwawunta cikakke",
    a5: "Kalli cikakken bidiyo",
    a6: "SHIGAR APP",
    a7: "Yarinya mai zafin jiki ta gwada jima’i na dubura kuma tana son kowane daƙiƙa. Kusa",
    a8: "Kalli cikakken bidiyo",
    a9: "SHIGAR APP",
    a10: "Sabon Zamani Mai Ban Mamaki",
    a11: "Kalli cikakken bidiyo",
    a12: "SHIGAR APP",
    a13: "Dole ne ka tabbatar cewa ka wuce shekaru 18",
    a14: "SOKA",
    a15: "KARBA",
    a16: "Raba a cikin Kungiyoyi 5 don tabbatar da cewa ka wuce 18",
    a17: "Raba a WhatsApp",
  },
  om: {
    a1: "Hunduuquu koo naan dhiitaa jikaa keessatti!!!",
    a2: "Viidiyoo guutuu ilaali",
    a3: "APP GALCHI",
    a4: "Obboleettii hunduuquu koo gogaa ishee qulqulluu tattaaffii akka ta’e beekti",
    a5: "Viidiyoo guutuu ilaali",
    a6: "APP GALCHI",
    a7: "Dubartiin qurxummii qabduu qoricha duburaa tattaaffiitii fi sekandii hundumtuu jaallatti. Qaxxaamura",
    a8: "Viidiyoo guutuu ilaali",
    a9: "APP GALCHI",
    a10: "Amajjii Haaraa Guddaa",
    a11: "Viidiyoo guutuu ilaali",
    a12: "APP GALCHI",
    a13: "Umuriin kee 18 ol ta’uu isaa mirkaneessuu qabda",
    a14: "DABALUU",
    a15: "FUDHATUU",
    a16: "Gareewwan 5tti qoodiitii umurii kee 18+ ta’uu kee mirkaneeffadhu",
    a17: "WhatsApp irratti qoodi",
  },
  zu: {
    a1: "Omunye engihlala naye uyangifaka kanzima ekhishini!!!",
    a2: "Buka ividiyo ephelele",
    a3: "FAKA UHLELO",
    a4: "Usisi wokuthatha uyazi ukuthi angalolonga kanjani izinqe zakhe eziphelele",
    a5: "Buka ividiyo ephelele",
    a6: "FAKA UHLELO",
    a7: "Intombazane enomzimba oshisayo izama ucansi lwendunu futhi iyayithanda yonke imizuzwana. Vala kakhulu",
    a8: "Buka ividiyo ephelele",
    a9: "FAKA UHLELO",
    a10: "Inkathi Entsha Emangalisayo",
    a11: "Buka ividiyo ephelele",
    a12: "FAKA UHLELO",
    a13: "Kumele uqinisekise ukuthi uneminyaka engaphezu kwe-18",
    a14: "KHANSELA",
    a15: "YAMUKELA",
    a16: "Yabelana ngezindawo eziyi-5 ukuqinisekisa ukuthi uneminyaka engu-18+",
    a17: "Yabelana ku-WhatsApp",
  },
  my: {
    a1: "အတူနေဖော်က မီးဖိုချောင်ထဲမှာ ကျွန်မကို ပြင်းပြင်းထန်ထန် လုပ်တယ်!!!",
    a2: "ဗီဒီယိုအပြည့်အစုံကြည့်ပါ",
    a3: "အက်ပ်ထည့်သွင်းပါ",
    a4: "အတူမွေးဖွားသူညီမက သူမရဲ့ပြီးပြည့်စုံတဲ့ တင်ပါးကို ဘယ်လိုလေ့ကျင့်ရမလဲဆိုတာ သိတယ်",
    a5: "ဗီဒီယိုအပြည့်အစုံကြည့်ပါ",
    a6: "အက်ပ်ထည့်သွင်းပါ",
    a7: "ခန္ဓာကိုယ်ပူပြင်းတဲ့ မိန်းကလေးက အနိုင်ယူလိင်ဆက်ဆံမှုကို စမ်းကြည့်ပြီး တစ်စက္ကန့်တိုင်းကို နှစ်သက်တယ်။ အနီးကပ်ရိုက်ကူးထားသည်",
    a8: "ဗီဒီယိုအပြည့်အစုံကြည့်ပါ",
    a9: "အက်ပ်ထည့်သွင်းပါ",
    a10: "ခေတ်သစ်အံ့သြဖွယ်",
    a11: "ဗီဒီယိုအပြည့်အစုံကြည့်ပါ",
    a12: "အက်ပ်ထည့်သွင်းပါ",
    a13: "သင်သည် ၁၈ နှစ်အထက်ဖြစ်ကြောင်း အတည်ပြုရပါမည်",
    a14: "ပယ်ဖျက်ပါ",
    a15: "လက်ခံပါ",
    a16: "သင် 18+ ဖြစ်ကြောင်းအတည်ပြုရန် 5 အဖွဲ့တွင်မျှဝေပါ",
    a17: "WhatsApp တွင်မျှဝေပါ",
  },
  km: {
    a1: "មិត្តរួមបន្ទប់ស្រលាញ់ខ្ញុំខ្លាំងនៅក្នុងផ្ទះបាយ!!!",
    a2: "មើលវីដេអូពេញ",
    a3: "ដំឡើងកម្មវិធី",
    a4: "បងស្រីចុងដឹងពីរបៀបហ្វឹកហាត់គូទដ៏ល្អឥតខ្ចោះរបស់នាង",
    a5: "មើលវីដេអូពេញ",
    a6: "ដំឡើងកម្មវិធី",
    a7: "នារីដែលមានរាងស្រស់ស្អាតសាកល្បងការរួមភេទតាមរន្ធគូទ ហើយស្រឡាញ់គ្រប់វិនាទី។ ថតជិត",
    a8: "មើលវីដេអូពេញ",
    a9: "ដំឡើងកម្មវិធី",
    a10: "សម័យថ្មីដ៏អស្ចារ្យ",
    a11: "មើលវីដេអូពេញ",
    a12: "ដំឡើងកម្មវិធី",
    a13: "អ្នកត្រូវតែបញ្ជាក់ថាអ្នកមានអាយុលើសពី ១៨ ឆ្នាំ",
    a14: "បោះបង់",
    a15: "ទទួលយក",
    a16: "ចែករំលែកក្នុង 5 ក្រុមដើម្បីបញ្ជាក់ថាអ្នកមានអាយុ 18+",
    a17: "ចែករំលែកលើ WhatsApp",
  },
  lo: {
    a1: "ຄູ່ຮ່ວມຫ້ອງມີເພດສຳພັນກັບຂ້ອຍຢ່າງແຮງຢູ່ໃນເຮືອນຄົວ!!!",
    a2: "ເບິ່ງວິດີໂອເຕັມ",
    a3: "ຕິດຕັ້ງແອັບ",
    a4: "ເອື້ອຍຕ່າງພໍ່ຮູ້ວິທີຝຶກຝົນກົ້ນທີ່ສົມບູນແບບຂອງນາງ",
    a5: "ເບິ່ງວິດີໂອເຕັມ",
    a6: "ຕິດຕັ້ງແອັບ",
    a7: "ສາວຮ່າງກາຍຮ້ອນລອງມີເພດສຳພັນທາງຮູທະວານ ແລະຮັກທຸກວິນາທີ. ໃກ້ຊິດ",
    a8: "ເບິ່ງວິດີໂອເຕັມ",
    a9: "ຕິດຕັ້ງແອັບ",
    a10: "ຍຸກໃໝ່ທີ່ປະທັບໃຈ",
    a11: "ເບິ່ງວິດີໂອເຕັມ",
    a12: "ຕິດຕັ້ງແອັບ",
    a13: "ທ່ານຕ້ອງຢືນຢັນວ່າທ່ານມີອາຍຸຫຼາຍກວ່າ 18 ປີ",
    a14: "ຍົກເລີກ",
    a15: "ຍອມຮັບ",
    a16: "ແບ່ງປັນໃນ 5 ກຸ່ມເພື່ອຢືນຢັນວ່າທ່ານມີອາຍຸ 18+",
    a17: "ແບ່ງປັນໃນ WhatsApp",
  },
  si: {
    a1: "රූම්මේට් මාව මුළුතැන්ගෙයේදී හයියෙන් බඳී!!!",
    a2: "සම්පූර්ණ වීඩියෝව නරඹන්න",
    a3: "යෙදුම ස්ථාපනය කරන්න",
    a4: "නැන්දම්මා ඇගේ පරිපූර්ණ ඉටිපන්දම පුහුණු කරන ආකාරය දන්නවා",
    a5: "සම්පූර්ණ වීඩියෝව නරඹන්න",
    a6: "යෙදුම ස්ථාපනය කරන්න",
    a7: "සරාගී රූපලාවන්‍ය ගැහැණිය ගුද සංසර්ගය උත්සාහ කරනවා සහ එහි එක් එක් තත්පරයට ආදරය කරයි. ආසන්න රූප",
    a8: "සම්පූර්ණ වීඩියෝව නරඹන්න",
    a9: "යෙදුම ස්ථාපනය කරන්න",
    a10: "නව ආකර්ෂණීය යුගය",
    a11: "සම්පූර්ණ වීඩියෝව නරඹන්න",
    a12: "යෙදුම ස්ථාපනය කරන්න",
    a13: "ඔබට වයස අවුරුදු 18 ට වැඩි බව තහවුරු කළ යුතුය",
    a14: "අවලංගු කරන්න",
    a15: "පිළිගන්න",
    a16: "ඔබ 18+ බව තහවුරු කිරීමට කණ්ඩායම් 5ක් තුළ බෙදාගන්න",
    a17: "WhatsApp මත බෙදාගන්න",
  },
  as: {
    a1: "ৰূমমেটে মোক পাকঘৰত জোৰেৰে চুদে!!!",
    a2: "পূৰ্ণ ভিডিঅ’ চাওক",
    a3: "এপ ইনষ্টল কৰক",
    a4: "ষ্টেপ চিষ্টাৰে জানে তাইৰ নিখুঁত পাছ কেনেকৈ প্ৰশিক্ষণ দিব লাগে",
    a5: "পূৰ্ণ ভিডিঅ’ চাওক",
    a6: "এপ ইনষ্টল কৰক",
    a7: "হট বডি বেবে পায়ু সংগমৰ চেষ্টা কৰে আৰু প্ৰতিটো ছেকেণ্ড ভাল পায়। ক্ল’জ-আপ",
    a8: "পূৰ্ণ ভিডিঅ’ চাওক",
    a9: "এপ ইনষ্টল কৰক",
    a10: "নতুন আচৰিত যুগ",
    a11: "পূৰ্ণ ভিডিঅ’ চাওক",
    a12: "এপ ইনষ্টল কৰক",
    a13: "আপুনি নিশ্চিত কৰিব লাগিব যে আপোনাৰ বয়স ১৮ বছৰৰ ওপৰত",
    a14: "বাতিল কৰক",
    a15: "গ্ৰহণ কৰক",
    a16: "আপুনি 18+ বুলি নিশ্চিত কৰিবলৈ 5 টা গোটত ভাগ কৰক",
    a17: "হোৱাটছএপত ভাগ কৰক",
  },
  or: {
    a1: "ରୁମମେଟ୍ ମୋତେ ରୋଷେଇ ଘରେ ଜୋରରେ ଚୁମ୍ବନ କରେ!!!",
    a2: "ପୂର୍ଣ୍ଣ ଭିଡିଓ ଦେଖନ୍ତୁ",
    a3: "ଆପ୍ ଇନଷ୍ଟଲ କରନ୍ତୁ",
    a4: "ଷ୍ଟେପ୍ ସିଷ୍ଟର ତାଙ୍କର ନିଖୁଣ ନିତମ୍ବକୁ କିପରି ତାଲିମ ଦେବେ ଜାଣିଛନ୍ତି",
    a5: "ପୂର୍ଣ୍ଣ ଭିଡିଓ ଦେଖନ୍ତୁ",
    a6: "ଆପ୍ ଇନଷ୍ଟଲ କରନ୍ତୁ",
    a7: "ହଟ୍ ବଡି ବେବ୍ ଗୁଦ ସଂଗମ ଚେଷ୍ଟା କରେ ଏବଂ ପ୍ରତ୍ୟେକ ସେକେଣ୍ଡକୁ ଭଲପାଏ। ନିକଟବର୍ତୀ ଶଟ୍",
    a8: "ପୂର୍ଣ୍ଣ ଭିଡିଓ ଦେଖନ୍ତୁ",
    a9: "ଆପ୍ ଇନଷ୍ଟଲ କରନ୍ତୁ",
    a10: "ନୂଆ ଅଦ୍ଭୁତ ଯୁଗ",
    a11: "ପୂର୍ଣ୍ଣ ଭିଡିଓ ଦେଖନ୍ତୁ",
    a12: "ଆପ୍ ଇନଷ୍ଟଲ କରନ୍ତୁ",
    a13: "ଆପଣଙ୍କୁ ନିଶ୍ଚିତ କରିବାକୁ ହେବ ଯେ ଆପଣଙ୍କର ବୟସ ୧୮ ବର୍ଷରୁ ଅଧିକ",
    a14: "ବାତିଲ କରନ୍ତୁ",
    a15: "ଗ୍ରହଣ କରନ୍ତୁ",
    a16: "ଆପଣ 18+ ବୋଲି ନିଶ୍ଚିତ କରିବାକୁ 5 ଗୋଷ୍ଠୀରେ ସେୟାର କରନ୍ତୁ",
    a17: "WhatsApp ରେ ସେୟାର କରନ୍ତୁ",
  },
  ps: {
    a1: "روم میټ ماته په پخلنځي کې سخت چودلی!!!",
    a2: "بشپړ ویډیو وګورئ",
    a3: "اپلیکیشن نصب کړئ",
    a4: "سوتیله خور پوهیږي چې خپله کامل کونډه څنګه روزنه وکړي",
    a5: "بشپړ ویډیو وګورئ",
    a6: "اپلیکیشن نصب کړئ",
    a7: "ګرمه نجلۍ مقعد جنسي هڅه کوي او هره ثانیه یې خوښوي. نږدې شاټ",
    a8: "بشپړ ویډیو وګورئ",
    a9: "اپلیکیشن نصب کړئ",
    a10: "نوی په زړه پوری دور",
    a11: "بشپړ ویډیو وګورئ",
    a12: "اپلیکیشن نصب کړئ",
    a13: "تاسو باید تصدیق کړئ چې ستاسو عمر له 18 کلونو څخه زیات دی",
    a14: "لغوه کړئ",
    a15: "قبول کړئ",
    a16: "د 18+ کیدو تصدیق کولو لپاره په 5 ګروپونو کې شریک کړئ",
    a17: "په واټساپ کې شریک کړئ",
  },
  ku: {
    a1: "Hevjîniya odeyê di mitbaxê de bi tundî min dike!!!",
    a2: "Vîdyoya tam temaşe bike",
    a3: "SEPANDÎ SAZ BIKE",
    a4: "Xwişka nîvî dizane çawa dûvika xwe ya bêkêmasî perwerde bike",
    a5: "Vîdyoya tam temaşe bike",
    a6: "SEPANDÎ SAZ BIKE",
    a7: "Keçika bi bedena germ cinsîyeta anal diceribîne û her çirkekê jê hez dike. Nêzîk",
    a8: "Vîdyoya tam temaşe bike",
    a9: "SEPANDÎ SAZ BIKE",
    a10: "Serdema nû ya ecêb",
    a11: "Vîdyoya tam temaşe bike",
    a12: "SEPANDÎ SAZ BIKE",
    a13: "Divê hûn piştrast bikin ku hûn ji 18 salî mezintir in",
    a14: "BETAL BIKE",
    a15: "QEBÛL BIKE",
    a16: "Ji bo piştrastkirina ku hûn ji 18 salî mezintir in, di 5 koman de parve bikin",
    a17: "Li ser WhatsApp parve bike",
  },
  ti: {
    a1: "ሓዳራይ ኣብ ወጥሃንጎ ብግብሪ ይሃርመኒ!!!",
    a2: "ምሉእ ቪድዮ ተመልከት",
    a3: "ኣፕ ስገር",
    a4: "ሓፍትኻ ንምንታይ ንቕንጸላ ፍጹም ድልድል ከመይ ጌርካ ትምህር ትፈልጥ",
    a5: "ምሉእ ቪድዮ ተመልከት",
    a6: "ኣፕ ስገር",
    a7: "ምቁር ኣካል ዘለዋ ጓል ዓቕሚ ጾታዊ ምርኻብ ተፈትን ንነፍሲ ወከፍ ሰከንድ ትፈትዎ። ቀረባ ምቅራብ",
    a8: "ምሉእ ቪድዮ ተመልከት",
    a9: "ኣፕ ስገር",
    a10: "ሓድሽ ዘደንቕ ዘመን",
    a11: "ምሉእ ቪድዮ ተመልከት",
    a12: "ኣፕ ስገር",
    a13: "ካብ 18 ዓመት ንላዕሊ ምዃንካ ኣረጋግጽ",
    a14: "ስረዝ",
    a15: "ተቐበል",
    a16: "ካብ 18 ዓመት ንላዕሊ ምዃንካ ንምርግጋጽ ኣብ 5 ጉጅለታት ኣካፍል",
    a17: "ኣብ WhatsApp ኣካፍል",
  },
  mg: {
    a1: "Ilay mpiara-mipetraka amiko dia manao firaisana amiko mafy ao an-dakozia!!!",
    a2: "Jereo ny video feno",
    a3: "APETRAHO NY APP",
    a4: "Ilay anabavy tsy tena izy dia mahay manao fanazarana ny vodiny lavorary",
    a5: "Jereo ny video feno",
    a6: "APETRAHO NY APP",
    a7: "Vehivavy manana vatana mafana dia manandrana firaisana anal ary tia ny segondra rehetra. Akaiky",
    a8: "Jereo ny video feno",
    a9: "APETRAHO NY APP",
    a10: "Ny vanim-potoana vaovao mahavariana",
    a11: "Jereo ny video feno",
    a12: "APETRAHO NY APP",
    a13: "Tsy maintsy manamarina ianao fa mihoatra ny 18 taona",
    a14: "HANAFOANA",
    a15: "EKEO",
    a16: "Zarao amin'ny Vondrona 5 mba hanamafisana fa mihoatra ny 18 taona ianao",
    a17: "Zarao amin'ny WhatsApp",
  },
  ny: {
    a1: "Wokhalamo naye amandipanga kwambiri kukhitchini!!!",
    a2: "Onani kanema wathunthu",
    a3: "IKANI PULOGALAMU",
    a4: "Mlongo wopeza amadziwa momwe angapangire matako ake abwino kwambiri",
    a5: "Onani kanema wathunthu",
    a6: "IKANI PULOGALAMU",
    a7: "Mtsikana wokongola amayesa kugonana ndi kumbuyo ndipo amakonda mphindi iliyonse. Poyandikira",
    a8: "Onani kanema wathunthu",
    a9: "IKANI PULOGALAMU",
    a10: "Nyengo yatsopano yodabwitsa",
    a11: "Onani kanema wathunthu",
    a12: "IKANI PULOGALAMU",
    a13: "Muyenera kutsimikizira kuti muli ndi zaka zopitirira 18",
    a14: "LETSA",
    a15: "VOMEREZA",
    a16: "Gawani m'magulu 5 kuti mutsimikizire kuti muli ndi zaka 18+",
    a17: "Gawana pa WhatsApp",
  },
  bh: {
    a1: "रूममेट हमके रसोई में जोर से चोदेला!!!",
    a2: "पूरा वीडियो देखीं",
    a3: "ऐप इंस्टॉल करीं",
    a4: "सौतेली बहिन जानत बा कि ऊ आपन सही गाँड़ के ट्रेनिंग कइसे करे",
    a5: "पूरा वीडियो देखीं",
    a6: "ऐप इंस्टॉल करीं",
    a7: "हॉट बडी वाली बेब गुदा सेक्स के कोशिश करत बा आ हर सेकेंड के मजा लेत बा। नजदीकी शॉट",
    a8: "पूरा वीडियो देखीं",
    a9: "ऐप इंस्टॉल करीं",
    a10: "नया शानदार युग",
    a11: "पूरा वीडियो देखीं",
    a12: "ऐप इंस्टॉल करीं",
    a13: "रउआ के पुष्टि करे के पड़त बा कि रउआ 18 साल से बड़ बानी",
    a14: "रद्द करीं",
    a15: "स्वीकार करीं",
    a16: "आप 18+ बानी, एकरा के पुष्टि करे खातिर 5 समूह में शेयर करीं",
    a17: "व्हाट्सएप पर शेयर करीं",
  },
  mai: {
    a1: "रूममेट हमरा के रसोई मे जोर से चोदैत अछि!!!",
    a2: "पूरा वीडियो देखू",
    a3: "ऐप इंस्टॉल करू",
    a4: "सौतेली बहिन जानैत छथि कि ओ अपन सही गाँड़ के प्रशिक्षण कइसे करी",
    a5: "पूरा वीडियो देखू",
    a6: "ऐप इंस्टॉल करू",
    a7: "हॉट बडी बेब गुदा सेक्स के कोशिश करैत छथि आ हर सेकेंड के मजा लैत छथि। नजदीकी शॉट",
    a8: "पूरा वीडियो देखू",
    a9: "ऐप इंस्टॉल करू",
    a10: "नया शानदार युग",
    a11: "पूरा वीडियो देखू",
    a12: "ऐप इंस्टॉल करू",
    a13: "अहाँ के पुष्टि करबाक चाही कि अहाँ 18 बरख से बेसी उमर के छी",
    a14: "रद्द करू",
    a15: "स्वीकार करू",
    a16: "अहाँ 18+ छी, एकर पुष्टि करबाक लेल 5 समूह मे शेयर करू",
    a17: "व्हाट्सएप पर शेयर करू",
  },
  mn: {
    a1: "Хамт амьдрагч намайг гал тогоонд хатуу тэврэнэ!!!",
    a2: "Бүрэн видеог үзэх",
    a3: "АПП СУУЛГАХ",
    a4: "Хойд эгч хэрхэн төгс хонгоо дасгалжуулахыг мэддэг",
    a5: "Бүрэн видеог үзэх",
    a6: "АПП СУУЛГАХ",
    a7: "Халуун биетэй охин хойд талын сексийг туршиж, секунд бүрт дурладаг. Ойрын зураг",
    a8: "Бүрэн видеог үзэх",
    a9: "АПП СУУЛГАХ",
    a10: "Шинэ гайхалтай эрин",
    a11: "Бүрэн видеог үзэх",
    a12: "АПП СУУЛГАХ",
    a13: "Та 18 наснаас дээш настай гэдгээ баталгаажуулах ёстой",
    a14: "ЦУЦЛАХ",
    a15: "ЗӨВШӨӨРӨХ",
    a16: "Та 18+ гэдгээ баталгаажуулахын тулд 5 бүлэгт хуваалцана уу",
    a17: "WhatsApp дээр хуваалцах",
  },
  so: {
    a1: "Qofka aan wada deganahay ayaa si adag iigu sameeyay jikada!!!",
    a2: "Daawo muuqaal buuxa",
    a3: "KU RAKIB APP",
    a4: "Walaashey xigta waxay taqaanaa sida loo tababaro dabada ugu fiican",
    a5: "Daawo muuqaal buuxa",
    a6: "KU RAKIB APP",
    a7: "Gabdhaha jirka kulul waxay isku dayaan galmada dabada waxayna jecelyihiin ilbiriqsi kasta. Sawir dhow",
    a8: "Daawo muuqaal buuxa",
    a9: "KU RAKIB APP",
    a10: "Xilliga cusub ee cajiibka ah",
    a11: "Daawo muuqaal buuxa",
    a12: "KU RAKIB APP",
    a13: "Waa inaad xaqiijisaa inaad ka weyn tahay 18 sano",
    a14: "JOOJI",
    a15: "AQBAL",
    a16: "Ku wadaag 5 Kooxood si aad u xaqiijiso inaad tahay +18",
    a17: "Ku wadaag WhatsApp",
  },
  ig: {
    a1: "Onye mụ na ya bi n’ụlọ na-akwado m ike n’ime kichin!!!",
    a2: "Lelee vidiyo zuru ezu",
    a3: "WỤNYE APP",
    a4: "Nwanne nwanyị nke abụghị nke mụrụ maara ka ọ ga-esi zụọ ike nke ya zuru oke",
    a5: "Lelee vidiyo zuru ezu",
    a6: "WỤNYE APP",
    a7: "Nwa agbọghọ nwere ahụ dị ọkụ na-anwale mmekọahụ n’ike ma na-amasị ya oge ọ bụla. Ihe dị nso",
    a8: "Lelee vidiyo zuru ezu",
    a9: "WỤNYE APP",
    a10: "Oge ọhụrụ dị egwu",
    a11: "Lelee vidiyo zuru ezu",
    a12: "WỤNYE APP",
    a13: "Ị ga-akwadorịrị na ị karịrị afọ 18",
    a14: "KAGBUO",
    a15: "NABATA",
    a16: "Kekọrịta na Group 5 iji gosi na ị karịrị afọ 18",
    a17: "Kekọrịta na WhatsApp",
  },
  ff: {
    a1: "Jom-ngalaa leydi nannde e mi e keewal!!!",
    a2: "Yiy widewoo guutuu",
    a3: "AAF APP",
    a4: "Wulɗo ngooɗirde yiyata no haa e nder moolaade maako",
    a5: "Yiy widewoo guutuu",
    a6: "AAF APP",
    a7: "Rewo moƴƴo e jeyka ɓanndi e gooto jara cinsii anal e njiyata kala yame. Ndenndaandi",
    a8: "Yiy widewoo guutuu",
    a9: "AAF APP",
    a10: "Nguurndam haaru ngam jamoore",
    a11: "Yiy widewoo guutuu",
    a12: "AAF APP",
    a13: "A foti tabitaade e nde a woni dow 18 nale",
    a14: "HAFTU",
    a15: "JAWDAA",
    a16: "Sefu haa e 5 kooɗe ngam tabitaade e nde a woni dow 18",
    a17: "Sefu haa e WhatsApp",
  },
  wo: {
    a1: "Sama waa kër biy samaan ci kusiin!!!",
    a2: "Wone widewoo bu paré",
    a3: "SAMPAL APP",
    a4: "Sama jabar ju xaral yepp yiw ci loxo ji mu am",
    a5: "Wone widewoo bu paré",
    a6: "SAMPAL APP",
    a7: "Jigeen bu ñuul ci jëkka jara anal ak mu mel ni mu bëgg kàddu bu neex. Ci diggante",
    a8: "Wone widewoo bu paré",
    a9: "SAMPAL APP",
    a10: "Yoon wi nder wi",
    a11: "Wone widewoo bu paré",
    a12: "SAMPAL APP",
    a13: "Fàww ci nga xam ne am nga 18 weer ak yépp",
    a14: "NAÑU",
    a15: "JÓGE",
    a16: "Joxe ci 5 mbootaay ngir wóor ne am nga 18+",
    a17: "Joxe ci WhatsApp",
  },
  bo: {
    a1: "ཁང་པའི་གནས་ཡོད་པའི་མི་མང་པོའི་གནས་ཡོད་པའི་མི་མང་པོའི་གནས་ཡོད།!!!",
    a2: "བརྙན་ཡིག་གནས་མཐོང་ཡོད།",
    a3: "ཆ་རིག་བཙུགས",
    a4: "མཚན་མཐའ་མཛེས་མཛེས་པའི་གནས་ཡོད།",
    a5: "བརྙན་ཡིག་གནས་མཐོང་ཡོད།",
    a6: "ཆ་རིག་བཙུགས",
    a7: "མཛེས་མཛེས་པའི་གནས་ཡོད་པའི་མི་མང་པོའི་གནས་ཡོད། བརྙན་ཡིག་གནས།",
    a8: "བརྙན་ཡིག་གནས་མཐོང་ཡོད།",
    a9: "ཆ་རིག་བཙུགས",
    a10: "ཡུག་པའི་གནས་ཡོད།",
    a11: "བརྙན་ཡིག་གནས་མཐོང་ཡོད།",
    a12: "ཆ་རིག་བཙུགས",
    a13: "ཁྱོད་ཀྱི་གནས་ཡོད་པའི་མི་མང་པོའི་གནས་ཡོད།",
    a14: "བཤིག",
    a15: "བཙུགས",
    a16: "ཁྱོད་ 18+ ཡིན་པ་ར་སྤྲོད་བྱ་བ་དང་ 5 ཚོགས་པ་ལ་བགོ་བཤའ་བྱོས།",
    a17: "WhatsApp ལ་བགོ་བཤའ་བྱོས།",
  },
  sm: {
    a1: "O la’u uo e fa’afefe a’u i le umukuka!!!",
    a2: "Matamata i le vitiō atoa",
    a3: "FA’APIPI’I APP",
    a4: "O le tuafafine fa’aopoopo e iloa le auala e a’oa’o ai lona mulilima atoatoa",
    a5: "Matamata i le vitiō atoa",
    a6: "FA’APIPI’I APP",
    a7: "O le teine aulelei e fa’ata’ita’i le feusuaiga i tua ma fiafia i sekone uma. Vaaiga vavalalata",
    a8: "Matamata i le vitiō atoa",
    a9: "FA’APIPI’I APP",
    a10: "Le Tausaga Fou Mata’utia",
    a11: "Matamata i le vitiō atoa",
    a12: "FA’APIPI’I APP",
    a13: "E tatau ona e fa’amaonia o lou matua e sili atu i le 18 tausaga",
    a14: "FAALEAOGA",
    a15: "TALIA",
    a16: "Fa'asoa i le 5 Vaega e fa'amaonia ai lou matua e sili atu i le 18 tausaga",
    a17: "Fa'asoa ile WhatsApp",
  },
};

window.onload = translate();
